#  __________           .___  .___      __________             .__       .__                           __
#  \______   \ ____   __| _/__| _/__.__.\______   \__ __  ____ |__| _____|  |__   _____   ____   _____/  |_  ______
#   |       _// __ \ / __ |/ __ <   |  | |     ___/  |  \/    \|  |/  ___/  |  \ /     \_/ __ \ /    \   __\/  ___/
#   |    |   \  ___// /_/ / /_/ |\___  | |    |   |  |  /   |  \  |\___ \|   Y  \  Y Y  \  ___/|   |  \  |  \___ \
#   |____|_  /\___  >____ \____ |/ ____| |____|   |____/|___|  /__/____  >___|  /__|_|  /\___  >___|  /__| /____  >
#          \/     \/     \/    \/\/                          \/        \/     \/      \/     \/     \/          \/
#
# SETTINGS.YML - This is where you change the settings of the plugin
#


# DO NOT TOUCH THIS
config-version: 1